### ISSUE TITLE
Jemalloc 5.0 compatibility

### ISSUE THREAD

**Issue by xfalcox** [be9/jemal#3]
Hi,

I was trying out Jemal with Jemalloc 5.0.1 (latest) loaded with `LD_PRELOAD` and got the following error:

```
irb(main):004:0> Jemal.stats_print
___ Begin jemalloc statistics ___
Version: 5.0.1-0-g896ed3a8b3f41998d4fb4d625d30ac63ef2d51fb
Assertions disabled
Run-time option settings:
  opt.abort: false
  opt.dss: "secondary"
  opt.stats_print: false
  opt.zero: false
  opt.tcache: true
  opt.lg_tcache_max: 15
CPUs: 4
Arenas: 16
Pointer size: 8
Quantum size: 16
Page size: 4096
<jemalloc>: Failure in xmallctl("opt.lg_dirty_mult", ...)
Aborted (core dumped)
```

Is there an update planned? Thanks for the gem!

**Comment by be9** [comment]
Hi @xfalcox, I haven't yet tried the gem with 5.x. PRs are welcome as always :) or you'll have to wait for bit.

**Comment by bronislav** [comment]
@be9 I'm experience following errors using gem with jemalloc 5:

```
#<Thread:0x00007f6f41f93b18@bin/worker:26 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from bin/worker:32:in `block in <main>'
	4: from bin/worker:32:in `loop'
	3: from bin/worker:34:in `block (2 levels) in <main>'
	2: from /usr/local/bundle/gems/jemal-0.1.1/lib/jemal.rb:164:in `stats'
	1: from /usr/local/bundle/gems/jemal-0.1.1/lib/jemal/interface.rb:131:in `read_size_t'
/usr/local/bundle/gems/jemal-0.1.1/lib/jemal/interface.rb:131:in `read_uint64': invalid memory read at address=0x0000000000000000 (FFI::NullPointerError)
```

I assume you don't have enough time to work on this gem. But may be you may suggest what approach I may use to debug it myself?

**Comment by bronislav** [comment]
I'm using jemalloc 5.0. I had to use gem version from master to make it working. The latest released version failing with error above.

@be9 It would be great if you cut a new release.

**Comment by rally25rs** [comment]
as @bronislav mentioned, `master` seems to work. So in your Gemfile use:
```
gem 'jemal', git: 'https://github.com/be9/jemal'
```

I am running against jemalloc `5.2.1`.
